### ISSUE TITLE
Having trouble traversing.

### ISSUE THREAD

**Issue by SimplyChris0930** [zlepper/itlt#36]
**How can we help?**
Write your question here
I’ve been trying to change the name of my mod pack on the client and also change the icon to my picture and I believe I’ve been struggle a lot with this mod. If anyone is available to help, I’d appreciate it. 
**Environment details**
Please fill in what you know, skipping any parts you don't know.
- Operating system (e.g. Windows 10):
- Java (e.g. AdoptOpenJDK 8 HotSpot):
- Mod version (e.g. 1.16.5-2.0.0):
- Minecraft version (e.g. 1.16.5):

**Comment by PaintNinja** [comment]
Sorry for the abnormally long delay. You haven't provided any details about your OS, what version of the mod you're using, your MC version, etc...

ITLT targets a very large range of Minecraft versions and operating systems, all of which work slightly differently both in terms of the config file and the underlying internals of the mod. I cannot give you specific instructions without knowing any details about what you're using.

If you're using a mod version of v2 or higher, this guide may help you: https://github.com/zlepper/itlt/wiki/Customising-your-modpack's-branding
For v1, there's this: https://github.com/zlepper/itlt/wiki/v1-docs

On v2 you usually just put an ICO, ICNS or PNG file in the itlt folder inside the config folder and call it "icon" (e.g. `config/itlt/icon.ico`) and enable the appropriate setting in the `config/itlt-client.toml` file so that it loads it.

On v1, it's the same as above but only PNG files are supported.

Depending on your Minecraft version and operating system (and its version), some features may no longer work. For example, you cannot change the dock icon on modern macOS in combination with ITLT for MC 1.8, as macOS has changed how setting the window icon works since then and Minecraft 1.8 still attempts to set it the old way.

If you still need a hand, please try to provide some details about what version of the mod you're using, what version of Minecraft you're using, what launcher you're using, etc...

**Comment by PaintNinja** [comment]
Closing due to no reply for a while, assuming last message was helpful and that you had no further questions.
