### ISSUE TITLE
Backported 1.2.5 Version Crash on World Load

### ISSUE THREAD

**Issue by CascadePanda** [zlepper/itlt#44]
Describe the bug
Loading a world with ITLT 1.2.5 causes a crash.

**To Reproduce**
1. Install itlt-1.2.5-1.0.0.jar with MultiMC.
2. Launch Minecraft through MultiMC.
3. Select "Singleplayer"
4. Create a new world, or load an existing world.
5. Wait for the world to load.

**Expected behavior**
Upon loading a world, the game will almost immediately go to "Saving Chunks" then the screen goes white.

**Environment details**
- Operating system: Windows 10
- Java: Build 1.8.0_371-b11
- Mod version: 1.2.5-1.0.0
- Minecraft version: 1.2.5

**Logs and additional context**
I used MultiMC to launch this since CurseForge's 1.2.5 version is currently non-functional, as staff member YOYOK9 explained on the official Discord server that "since 1.2.5 is so old, the files for the modloader forge are either missing or have broken paths. Sadly Forge wont help with this either as its outdated"

MultiMC crash log:
[crash.log](https://github.com/zlepper/itlt/files/12072383/crash.log)

**Comment by PaintNinja** [comment]
Thanks for your bug report. According to your log, the issue is caused by a different mod having broken code related to entity sounds. As ITLT does not touch sound code in MC, you should do a binary search to find the problematic mod.
> 023-07-17 10:38:30 [SEVERE] A critical error has occurred.
> java.lang.RuntimeException: Minecraft Forge: Interface check in onPlaySoundAtEntity, remove it Mods should be updated

To do a binary search:
1. Make a backup of your world, config and mods folders
2. Delete half the mods, see if it works now.
3. If yes: try the other half. If no: keep splitting in half until you find the broken mod.
4. Once you've found the broken mod, restore the backup made in step 1 and delete that one mod

**Comment by CascadePanda** [comment]
Thank you for the reply. I tried running the game with only ITLT in my load order (other than Forge, obviously) and it throws a very similar error.
[MultiMC Log2.txt](https://github.com/zlepper/itlt/files/12112906/MultiMC.Log2.txt)

**Comment by PaintNinja** [comment]
In that case, it appears your Forge install is broken

**Comment by PaintNinja** [comment]
Could you try Java 7? I don't think Forge on 1.2.5 supports Java 8.
https://www.azul.com/downloads/?version=java-7-lts&architecture=x86-64-bit&package=jdk#zulu
